#!/bin/bash
# setup-ansible-user
# Cria usario ansible para automação Ansible 
# e gerenciamento configuracao.
# Cria ansible user
getentUser=$(/usr/bin/getent passwd ansible)
if [ -z "$getentUser" ]
then
  echo "Usuario ansible nao existe.  Sera incluido.."
  /usr/sbin/groupadd -g 4445 ansible
  /usr/sbin/useradd -u 4445 -g 4445 -c "Ansible Automation Account" -s /bin/bash -m -d /home/ansible ansible
fi

# Força o UID e o GID
usermod -u 4445 ansible
groupmod -g 4445 ansible

# troca senha do usuario
echo "ansible:$1" | /usr/sbin/chpasswd

DIRSSH="/home/ansible/.ssh"
if [ -d "$DIRSSH" ]; then
  echo "O diretório $DIRSSH existe."
else
  echo "O diretório $DIRSSH não existe. Será criado"
  mkdir -p $DIRSSH
fi

# Verifica se o diretorio sudoers esta presente
DIR="/etc/sudoers.d"

if [ -d "$DIR" ]; then
  echo "O diretório $DIR existe."
else
  echo "O diretório $DIR não existe. Será criado"
  mkdir -p $DIR
fi

# Verifica se a pasta /etc/ansible existe
if [ -d "/etc/ansible" ]; then
    echo "A pasta /etc/ansible já existe. Copiando o arquivo ansible.cfg..."
else
    echo "A pasta /etc/ansible não existe. Criando a pasta..."
    mkdir -p /etc/ansible
    chmod 644 -R /etc/ansible
fi

# Copia o arquivo ansible.cfg para /etc/ansible
pwd
cp /tmp/ansible.cfg /etc/ansible/

# setup ssh authorization keys for Ansible access 
echo "Configurando ssh authorization keys..."
cat << 'EOF' >> /home/ansible/.ssh/authorized_keys
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJvaUICPun0zJo21vhsvaZpYegvpzZjxxkMQxPOF5xeL user_svc_puppet.sof.intra
EOF
# Copia a chave publica e privada do ansible
arquivo_origem="/tmp/id_ed25519"
pasta_destino="/home/ansible/.ssh"

if [ -e "$arquivo_origem" ]; then
    cp "$arquivo_origem" "$pasta_destino"
    cp "$arquivo_origem.pub" "$pasta_destino"
    echo "Arquivo copiado com sucesso."
else
    echo "O arquivo "$arquivo_origem" não existe."
fi

chown -R ansible:ansible /home/ansible/.ssh
chmod 700 /home/ansible/.ssh
chmod 600 /home/ansible/.ssh/id_ed25519
chmod 644 /home/ansible/.ssh/id_ed25519.pub
# setup sudo access for Ansible
if [ ! -s $DIR/ansible ]
then
  echo "Usuario ansible nao existe.  Sera incluido.."
  cat << 'EOF' > $DIR/ansible
  User_Alias ANSIBLE_AUTOMATION = ansible
  Defaults:ANSIBLE_AUTOMATION !requiretty
  ANSIBLE_AUTOMATION ALL=(ALL) NOPASSWD: ALL
EOF
chmod 400 $DIR/ansible
fi
# end of script
exit 0

